package com.example.sos_segundoplano.wear

import androidx.test.platform.app.InstrumentationRegistry
import com.example.sos_segundoplano.wearprotocol.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import org.junit.Assert.*
import org.junit.Test

class MobileCompanionGatewayTest {
    @Test fun nearbyNodeIsPreferred() = runBlocking { val t=transport(stateResponse("r1")); gateway(listOf(n("node-z",false),n("node-b",true),n("node-a",true)),t,{"r1"}).getTripState(); assertEquals("node-a",t.node) }
    @Test fun lowestNodeIdIsSelectedWhenNoNodeIsNearby() = runBlocking { val t=transport(stateResponse("r1")); gateway(listOf(n("node-z",false),n("node-b",false),n("node-a",false)),t,{"r1"}).getTripState(); assertEquals("node-a",t.node) }
    @Test fun noCapabilityNodesReturnsCompanionUnavailable() = runBlocking { val t=transport(ByteArray(0)); assertEquals(MobileCompanionResult.CompanionUnavailable,gateway(emptyList(),t,{"r1"}).getTripState()); assertEquals(0,t.calls) }
    @Test fun getTripStateUsesCorrectPathAndDecodesResponse() = runBlocking { val t=transport(stateResponse("request-state-gateway-001")); val r=gateway(listOf(n()),t,{"request-state-gateway-001"}).getTripState(); assertTrue(r is MobileCompanionResult.Success); assertEquals(WearProtocol.PATH_TRIP_STATE,t.path); assertEquals("request-state-gateway-001",(WearActionProtocolCodec.decodeTripStateRequest(t.payload!! ) as WearDecodeResult.Success).value.requestId) }
    @Test fun startTripPreservesCommandIdAndUsesNewRequestId() = runBlocking { val t=transport(actionResponse("request-start-001")); gateway(listOf(n()),t,{"request-start-001"}).startTrip("command-start-gateway-777"); val q=(WearActionProtocolCodec.decodeStartTripAction(t.payload!!) as WearDecodeResult.Success).value; assertEquals(WearProtocol.PATH_ACTION_START_TRIP,t.path); assertEquals("command-start-gateway-777",q.commandId); assertEquals("request-start-001",q.requestId) }
    @Test fun startTripRetryKeepsCommandIdButGeneratesNewRequestId() = runBlocking { val ids=ArrayDeque(listOf("request-start-001","request-start-002")); val t=CapturingTransport { actionResponse(ids.first()) }; val g=gateway(listOf(n()),t,{ids.removeFirst()}); g.startTrip("command-start-shared"); val a=(WearActionProtocolCodec.decodeStartTripAction(t.payloads[0]) as WearDecodeResult.Success).value; g.startTrip("command-start-shared"); val b=(WearActionProtocolCodec.decodeStartTripAction(t.payloads[1]) as WearDecodeResult.Success).value; assertEquals(a.commandId,b.commandId); assertEquals("request-start-001",a.requestId); assertEquals("request-start-002",b.requestId) }
    @Test fun finishTripPreservesConfirmedRemoteTripId() = runBlocking { val t=transport(actionResponse("r")); gateway(listOf(n()),t,{"r"}).finishTrip("command-finish-001","trip-gateway-123"); val q=(WearActionProtocolCodec.decodeFinishTripAction(t.payload!!) as WearDecodeResult.Success).value; assertEquals(WearProtocol.PATH_ACTION_FINISH_TRIP,t.path); assertEquals("trip-gateway-123",q.remoteTripId) }
    @Test fun manualSosPreservesConfirmedRemoteTripId() = runBlocking { val t=transport(actionResponse("r",WearProtocol.PATH_ACTION_MANUAL_SOS)); gateway(listOf(n()),t,{"r"}).manualSos("command-sos-001","trip-gateway-123"); val q=(WearActionProtocolCodec.decodeManualSosAction(t.payload!!) as WearDecodeResult.Success).value; assertEquals(WearProtocol.PATH_ACTION_MANUAL_SOS,t.path); assertEquals("trip-gateway-123",q.remoteTripId) }
    @Test fun manualSosDecodesPhoneOkAndRetryKeepsCommandWithNewRequestId() = runBlocking { val ids=ArrayDeque(listOf("request-sos-001","request-sos-002")); val responses=ArrayDeque(listOf("request-sos-001","request-sos-002")); val t=CapturingTransport { actionResponse(responses.removeFirst(),WearProtocol.PATH_ACTION_MANUAL_SOS) }; val g=gateway(listOf(n()),t,{ids.removeFirst()}); val first=g.manualSos("command-sos-shared","trip-gateway-123"); val a=(WearActionProtocolCodec.decodeManualSosAction(t.payloads[0]) as WearDecodeResult.Success).value; val retry=g.manualSos("command-sos-shared","trip-gateway-123"); val b=(WearActionProtocolCodec.decodeManualSosAction(t.payloads[1]) as WearDecodeResult.Success).value; assertEquals(PhoneActionResult.OK,(first as MobileCompanionResult.Success).value.result); assertEquals(PhoneActionResult.OK,(retry as MobileCompanionResult.Success).value.result); assertEquals(a.commandId,b.commandId); assertEquals("request-sos-001",a.requestId); assertEquals("request-sos-002",b.requestId) }
    @Test fun mismatchedResponseRequestIdReturnsDecodeFailure() = runBlocking { assertEquals(MobileCompanionResult.DecodeFailure,gateway(listOf(n()),transport(actionResponse("other")),{"expected"}).startTrip("c")) }
    @Test fun malformedResponseReturnsDecodeFailure() = runBlocking { assertEquals(MobileCompanionResult.DecodeFailure,gateway(listOf(n()),transport(byteArrayOf(1,2)),{"r"}).getTripState()) }
    @Test fun transportFailureIsTyped() = runBlocking { assertEquals(MobileCompanionResult.TransportFailure,gateway(listOf(n()),CapturingTransport { throw IllegalStateException() },{"r"}).getTripState()) }
    @Test fun requestTimeoutReturnsTimeout() = runBlocking { assertEquals(MobileCompanionResult.Timeout,gateway(listOf(n()),CapturingTransport { delay(20); stateResponse("r") },{"r"},1).getTripState()) }
    private fun gateway(nodes:List<CompanionNode>, t:CapturingTransport, ids:()->String, timeout:Long=5_000)=MobileCompanionGateway(InstrumentationRegistry.getInstrumentation().targetContext,ids,timeout,CompanionNodeSource{nodes},t)
    private fun n(id:String="node-a",near:Boolean=true)=CompanionNode(id,near)
    private fun stateResponse(id:String)=WearActionProtocolCodec.encodeTripStateResponse(TripStateResponse(id,false,null,null,1,PhoneActionResult.OK))
    private fun actionResponse(id:String,path:String=WearProtocol.PATH_ACTION_START_TRIP)=WearActionProtocolCodec.encodePhoneActionResponse(path,PhoneActionResponse(id,PhoneActionResult.OK,respondedAtEpochMs=1))
    private fun transport(bytes:ByteArray)=CapturingTransport{bytes}
    private class CapturingTransport(private val reply:suspend ()->ByteArray):CompanionRequestTransport { var node:String?=null; var path:String?=null; var payload:ByteArray?=null; val payloads=mutableListOf<ByteArray>(); var calls=0; override suspend fun sendRequest(nodeId:String,path:String,payload:ByteArray):ByteArray { calls++;node=nodeId;this.path=path;this.payload=payload;payloads+=payload;return reply() } }
}
